default_language_version:
  python: python3.11

files: ^python_template/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/myint/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        language: system